@server=http://localhost:3002

### get unique id
# @name requestID
GET {{server}}/id/get/unique HTTP/1.1
### set unique id
@unique_id={{requestID.response.body.$.id}}

### user out
POST {{server}}/point/set HTTP/1.1
Content-Type: application/json

{
    "id": "{{unique_id}}",
    "type": "user",
    "lat" : "7.131219707506233",
    "lng" : "-73.11853203010241"
}

### user in
POST  {{server}}/coordinates HTTP/1.1
Content-Type: application/json

{
    "coordinates": { 
        "latitude" : 7.131354518128816,
        "longitude" : -73.11778878718832
    },
    "user_id": "test/120m4n",
    "unique_id": "abcd1234",
    "fleet":"avatar"
}

### avatar step 2 in
POST  {{server}}/coordinates HTTP/1.1
Content-Type: application/json

{
  "coordinates": { 
    "latitude": 7.1301016117887315,
    "longitude": -73.1217566850091
  },
  "user_id": "test/120m4n",
  "unique_id": "abcd1234",
  "fleet":"avatar"
}

### user in
POST {{server}}/point/unset HTTP/1.1
Content-Type: application/json

{
    "id": "{{requestID.response.body.$.id}}",
    "type": "user"
}

### set detection POI 1 (point of interest)
POST {{server}}/detection/set HTTP/1.1
Content-Type: application/json

{
    "type": "avatar",
    "detection_id" : "poi_1",
    "latitude": 7.134611389344414,
    "longitude": -73.1179759318848,
    "radius" : 50,
    "trigger" : ["enter", "exit"]
    
}

### set detection POI 2 (point of interest)
POST {{server}}/detection/set HTTP/1.1
Content-Type: application/json

{
    "type": "avatar",
    "detection_id" : "poi_2",
    "latitude": 7.129857835868549,
    "longitude": -73.12296347107322,
    "radius" : 30,
    "trigger" : ["enter", "exit"]
    
}


### set detection POI 3 (point of interest)
POST {{server}}/detection/set HTTP/1.1
Content-Type: application/json

{
    "type": "avatar",
    "detection_id" : "poi_3",
    "latitude": 7.128544822285939,
    "longitude": -73.12086892933067,
    "radius" : 127,
    "trigger" : ["enter", "exit"]
    
}

### set detection codeplus
POST {{server}}/codeplus/set HTTP/1.1
Content-Type: application/json

{
    "type": "avatar",
    "code_plus":"67V84VJJ+",
    "trigger" : ["enter", "exit"]
}



### set fence detection 
POST {{server}}/geofence/set HTTP/1.1
Content-Type: application/json

{
    "type": "avatar",
    "fence_id" : "zona_1",
    "trigger": ["enter", "exit"],
    "geojson": "{\"features\":[{\"geometry\":{\"coordinates\":[[[-73.1216394332437,7.13119952392347],[-73.1214317370815,7.13033504886904],[-73.1222605549802,7.13012436431809],[-73.1219726979696,7.12897353916928],[-73.1200355696902,7.12946526111591],[-73.1205070746098,7.13143513239987],[-73.1216394332437,7.13119952392347]]],\"type\":\"Polygon\"},\"properties\":{\"Name\":\"zona_1\"},\"type\":\"Feature\"}],\"type\":\"FeatureCollection\"}"
}

### set fence detection
POST {{server}}/geofence/set HTTP/1.1
Content-Type: application/json

{
    "type": "avatar",
    "fence_id" : "zona_2",
    "trigger": ["enter", "exit"],
    "geojson": "{\"features\":[{\"geometry\":{\"coordinates\":[[[-73.119264941439,7.12851479693417],[-73.1202156710847,7.12806148390395],[-73.1202403653599,7.12672604556394],[-73.1189809573275,7.12613796138973],[-73.1182895176236,7.12664028333525],[-73.1179684920462,7.12791446335966],[-73.1183018647608,7.12845353845816],[-73.119264941439,7.12851479693417]]],\"type\":\"Polygon\"},\"properties\":{\"Name\":\"zona_2\"},\"type\":\"Feature\"}],\"type\":\"FeatureCollection\"}"
}




### get geofence
GET {{server}}/geofences/get HTTP/1.1