services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geo_server
    ports:
      - 3002:3002
    environment:
      - NATS_ADDRESS=dev_nats_server
      - TILE38_ADDRESS=dev_tile38_server
      - SERVER_ADDRESS=192.168.1.95
      - SERVER_PORT=3002
    depends_on:
      - dev_nats_server

  dev_nats_server:
    image: nats:latest
    container_name: dev_nats_server
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      
  dev_tile38_server:
    image: tile38/tile38
    container_name: dev_tile38_server
    volumes:
      - dev-tile38-data:/data
    command: ["tile38-server", "-d", "/data"]
    ports:
      - 9851:9851
    healthcheck:
      test: ["CMD", "tile38-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  dev_coordinates_worker:
    image: electrosoftware/coordinates_worker:latest
    container_name: dev_coordinates_worker
    environment:
      - NATS_URL=nats://dev_nats_server:4222
      - MONGO_URI=mongodb://root:example@dev_mongo_server:27017
  dev_mongo_server:
    image: mongo
    container_name: dev_mongo_server
    restart: always    
    ports:
      - 27017:27017
    volumes:
      - dev-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    
volumes:
  dev-tile38-data:
  dev-mongo-data: