services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geo_server
    ports:
      - 3002:3002
    environment:
      - NATS_ADDRESS=dev_nats_server
      - TILE38_ADDRESS=dev_tile38_server
      - SERVER_PORT=3002

  dev_nats_server:
    image: nats:latest
    container_name: dev_nats_server
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      
  dev_tile38_server:
    image: tile38/tile38
    container_name: dev_tile38_server
    volumes:
      - dev-tile38-data:/data
    command: ["tile38-server", "-d", "/data"]
    ports:
      - 9851:9851
    healthcheck:
      test: ["CMD", "tile38-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  dev-tile38-data: