services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 3002:3002
    # volumes:
    #   - ./public:/public
    networks:
      - network_geosmartsystem
    environment:
      - GIN_MODE=release
      - SERVER_ADDRESS=server
      - SERVER_PORT=3002
      - TILE38_ADDRESS=tile38_server
      - TILE38_PORT=9851
      - NATS_ADDRESS=172.31.0.2
    depends_on:
      - tile38_server
  tile38_server:
    image: tile38/tile38
    container_name: tile38_server
    # volumes:
    #   - tile38-data:/data
    networks:
      - network_geosmartsystem
    command: ["tile38-server", "-d", "/data"]
    healthcheck:
      test: ["CMD", "tile38-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  network_geosmartsystem:
    external: true
