@server=http://127.0.0.1:8080

### get unique id
# @name requestID
GET {{server}}/id/get/unique HTTP/1.1
### set unique id
@unique_id={{requestID.response.body.$.id}}

### user out
POST {{server}}/point/set HTTP/1.1
Content-Type: application/json

{
    "id": "{{unique_id}}",
    "type": "user",
    "lat" : "7.131219707506233",
    "lng" : "-73.11853203010241"
}

### user in
POST {{server}}/point/set HTTP/1.1
Content-Type: application/json

{
    "id": "{{unique_id}}",
    "type": "user",
    "lat" : "7.131354518128816",
    "lng" : "-73.11778878718832"
}

### user in
POST {{server}}/point/unset HTTP/1.1
Content-Type: application/json

{
    "id": "{{requestID.response.body.$.id}}",
    "type": "user"
}

### set detection 
POST {{server}}/detection/set HTTP/1.1
Content-Type: application/json

{
    "type": "user",
    "lat" : "7.1308",
    "lng" : "-73.119994194",
    "trigger" : ["enter", "exit"],
    "radius" : "100"
}



### set fence detection 
POST {{server}}/geofence/set HTTP/1.1
Content-Type: application/json

{
    "type": "user",
    "fence_id" : "zona_1",
    "trigger": ["enter", "exit"],
    "geojson": "{\"features\":[{\"geometry\":{\"coordinates\":[[[-73.1214614531143,7.13101274281496],[-73.1212988009966,7.13021555364789],[-73.1221317769915,7.13000036124185],[-73.1219001209458,7.1291591535955],[-73.1202588132165,7.1294917242448],[-73.1206186194149,7.13119369967171],[-73.1214614531143,7.13101274281496]]],\"type\":\"Polygon\"},\"properties\":{\"Name\": \"zona_1\"},\"type\":\"Feature\"}],\"type\":\"FeatureCollection\"}"
}

### set fence detection
POST {{server}}/geofence/set HTTP/1.1
Content-Type: application/json

{
    "type": "user",
    "fence_id" : "zona_2",
    "trigger": ["enter", "exit"],
    "geojson": "{\"features\":[{\"geometry\":{\"coordinates\":[[[-73.118990925955,7.13154108554438],[-73.1188390806288,7.13066878116814],[-73.1180958377148,7.13081945204242],[-73.1182237074634,7.13165210598153],[-73.118990925955,7.13154108554438]]],\"type\":\"Polygon\"},\"properties\":{\"Name\": \"zona_2\"},\"type\":\"Feature\"}],\"type\":\"FeatureCollection\"}"
}




### get geofence
GET {{server}}/geofences/get HTTP/1.1